### ISSUE TITLE
evil portal autorize all clients

### ISSUE THREAD

**Issue by Rorschach007** [frozenjava/EvilPortalNano#31]
allways when i turn on the evil portal the clients see the portal but they can use whitout login

**Comment by wpa-2** [comment]
Sadly it's a known issue and hasn't been fixed, Hopefully it will get sorted soon if it can be.

**Comment by H4xl0r** [comment]
fixed with the new version 
@frozenjava please close this 

its a portal issue not evilportal itself !

have a look on the portals here : 
https://github.com/kbeflo/evilportals
they are checking the input / if there is a input or not 
form needs some input infos 
like : 

```
<input id="user" type="text" name="email" placeholder="Enter your email"  _autofocus="true" autocorrect="off" autocomplete="off" autocapitalize="off" required>
<input type="password" name="password" placeholder="Enter your password" autocorrect="off" autocomplete="off" autocapitalize="off" required>

```
the required info says the system there is a input needed ! 
backcheck iand warning is done via : 

`<p class="warning"><?php echo !empty($err)?$err:"&nbsp;";?></p>`

so if your form is accepting clients without input check your from / compare it with the one from 
https://github.com/kbeflo/evilportals

they dont submit the post without input !
thats the solution to your problems i guess

**Comment by Rorschach007** [comment]
great, i will test it right now
